-- 01. 모든 레코드 조회하기
SELECT * FROM ANIMAL_INS ORDER BY ANIMAL_ID ASC;
-- ASC : 오름차순 / DESC : 내림차순 ... 기본 값은 


-- 02. 역순 정렬 및 필드 선택
SELECT NAME, DATETIME FROM ANIMAL_INS ORDER BY ANIMAL_ID DESC;


-- 03. 아픈 동물 찾기 ( WHERE절 = 연산자 
SELECT ANIMAL_ID, NAME FROM ANIMAL_INS WHERE INTAKE_CONDITION = "Sick";


-- 04. 어린 동물 찾기 ( WHERE절 != 연산자 )
SELECT ANIMAL_ID, NAME FROM ANIMAL_INS WHERE INTAKE_CONDITION != "Aged";


-- 05. 동물의 아이디가 이름 
SELECT ANIMAL_ID, NAME FROM ANIMAL_INS ORDER BY ANIMAL_ID ASC;


-- 06. 여러 기준으로 정렬 ( ,로 구분 오름차/내림차는 각각 적어주기 )
SELECT ANIMAL_ID, NAME, DATETIME FROM ANIMAL_INS ORDER BY NAME ASC, DATETIME DESC;


-- 07. 상위 n개 레코드
-- oracle : 서브쿼리
SELECT NAME FROM ( SELECT NAME FROM ANIMAL_INS ORDER BY DATETIME ) WHERE ROWNUM <= 1;
-- 다른 방식으로 FETCH FIRST n ROW(S) ONLY 사용
SELECT NAME FROM ANIMAL_INS ORDER BY DATETIME FETCH FIRST 1 ROW ONLY;

-- oracle, mysql : min() 함수 사용 
SELECT NAME from ANIMAL_INS where DATETIME = (select min(DATETIME) from ANIMAL_INS);

-- mysql LIMIT 사용
SELECT NAME FROM ANIMAL_INS ORDER BY DATETIME LIMIT 1

