-- 01. 없어진 기록 찾기
-- 조인 조건문은 ON절에 !! ( 보통 pk = fk )
-- 조인 후 조건문은 WHERE 절 !! 
SELECT A.ANIMAL_ID, A.NAME FROM ANIMAL_OUTS A 
LEFT OUTER JOIN ANIMAL_INS B
ON A.ANIMAL_ID = B.ANIMAL_ID 
WHERE B.ANIMAL_ID IS NULL;


-- 02. 있었는데요 없었습니다
SELECT A.ANIMAL_ID, A.NAME FROM ANIMAL_INS A 
JOIN ANIMAL_OUTS B ON A.ANIMAL_ID = B.ANIMAL_ID
WHERE A.DATETIME > B.DATETIME
ORDER BY A.DATETIME;


-- 03. 오랜 기간 보호한 동물 
SELECT A.NAME, A.DATETIME FROM ANIMAL_INS A
LEFT OUTER JOIN ANIMAL_OUTS B ON A.ANIMAL_ID = B.ANIMAL_ID
WHERE B.ANIMAL_ID IS NULL
ORDER BY A.DATETIME
LIMIT 3;


-- 04. 보호소에서 중성화한 동물
SELECT A.ANIMAL_ID, A.ANIMAL_TYPE, A.NAME FROM ANIMAL_INS A
LEFT OUTER JOIN ANIMAL_OUTS B ON A.ANIMAL_ID = B.ANIMAL_ID
WHERE A.SEX_UPON_INTAKE != B.SEX_UPON_OUTCOME
ORDER BY A.ANIMAL_ID;
-- like / not like 연산자 풀이
SELECT A.ANIMAL_ID, A.ANIMAL_TYPE, A.NAME FROM ANIMAL_OUTS A 
JOIN ANIMAL_INS B
ON A.ANIMAL_ID = B.ANIMAL_ID
WHERE A.SEX_UPON_OUTCOME NOT LIKE 'Intact%'
AND B.SEX_UPON_INTAKE LIKE 'Intact%'
ORDER BY A.ANIMAL_ID;